version: '3.4'

services:
  oracledb:
    image: gvenzl/oracle-free:23
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-volume:/opt/oracle/oradata

  webapi:
    build: ./api
    container_name: webapi
    ports:
      - "5000:8080"
    depends_on:
      - oracledb
    environment:
      - ConnectionStrings__DefaultConnection=User Id=system;Password=oracle;Data Source=oracle:1521/FREEPDB1;

volumes:
  oracle-volume:
