version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_DATABASE=FREEPDB1
      - APP_USER=system
      - APP_USER_PASSWORD=oracle
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thefirm-api
    depends_on:
      - oracle
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOCKER_ENVIRONMENT=true
    ports:
      - "5000:80"
    restart: unless-stopped

volumes:
  oracle-data: 